server:
  port: 8080
  mode: debug
  jwt_secret: "super-secret-key-for-dev"

db:
  host: localhost
  port: 5432
  user: postgres
  password: password
  name: nexia_db
  ssl_mode: disable

ai:
  gemini_api_key: ""
  redis_url: "127.0.0.1:6379"
