// Code generated by MockGen. DO NOT EDIT.
// Source: nexia-backend/internal/services (interfaces: GeminiClient,VectorSearchClient,EmbeddingGenerator,EmbeddingRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/services/mock_services_test.go -package=services_test nexia-backend/internal/services GeminiClient,VectorSearchClient,EmbeddingGenerator,EmbeddingRepository
//

// Package services_test is a generated GoMock package.
package services_test

import (
	context "context"
	models "nexia-backend/internal/models"
	repositories "nexia-backend/internal/repositories"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGeminiClient is a mock of GeminiClient interface.
type MockGeminiClient struct {
	ctrl     *gomock.Controller
	recorder *MockGeminiClientMockRecorder
	isgomock struct{}
}

// MockGeminiClientMockRecorder is the mock recorder for MockGeminiClient.
type MockGeminiClientMockRecorder struct {
	mock *MockGeminiClient
}

// NewMockGeminiClient creates a new mock instance.
func NewMockGeminiClient(ctrl *gomock.Controller) *MockGeminiClient {
	mock := &MockGeminiClient{ctrl: ctrl}
	mock.recorder = &MockGeminiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeminiClient) EXPECT() *MockGeminiClientMockRecorder {
	return m.recorder
}

// GenerateChatResponse mocks base method.
func (m *MockGeminiClient) GenerateChatResponse(ctx context.Context, systemPrompt, userMessage string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateChatResponse", ctx, systemPrompt, userMessage)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateChatResponse indicates an expected call of GenerateChatResponse.
func (mr *MockGeminiClientMockRecorder) GenerateChatResponse(ctx, systemPrompt, userMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateChatResponse", reflect.TypeOf((*MockGeminiClient)(nil).GenerateChatResponse), ctx, systemPrompt, userMessage)
}

// GenerateEmbedding mocks base method.
func (m *MockGeminiClient) GenerateEmbedding(ctx context.Context, text string) ([]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateEmbedding", ctx, text)
	ret0, _ := ret[0].([]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateEmbedding indicates an expected call of GenerateEmbedding.
func (mr *MockGeminiClientMockRecorder) GenerateEmbedding(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateEmbedding", reflect.TypeOf((*MockGeminiClient)(nil).GenerateEmbedding), ctx, text)
}

// MockVectorSearchClient is a mock of VectorSearchClient interface.
type MockVectorSearchClient struct {
	ctrl     *gomock.Controller
	recorder *MockVectorSearchClientMockRecorder
	isgomock struct{}
}

// MockVectorSearchClientMockRecorder is the mock recorder for MockVectorSearchClient.
type MockVectorSearchClientMockRecorder struct {
	mock *MockVectorSearchClient
}

// NewMockVectorSearchClient creates a new mock instance.
func NewMockVectorSearchClient(ctrl *gomock.Controller) *MockVectorSearchClient {
	mock := &MockVectorSearchClient{ctrl: ctrl}
	mock.recorder = &MockVectorSearchClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVectorSearchClient) EXPECT() *MockVectorSearchClientMockRecorder {
	return m.recorder
}

// SearchContext mocks base method.
func (m *MockVectorSearchClient) SearchContext(ctx context.Context, userID uint64, queryEmbedding []float32, limit int) ([]repositories.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchContext", ctx, userID, queryEmbedding, limit)
	ret0, _ := ret[0].([]repositories.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchContext indicates an expected call of SearchContext.
func (mr *MockVectorSearchClientMockRecorder) SearchContext(ctx, userID, queryEmbedding, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchContext", reflect.TypeOf((*MockVectorSearchClient)(nil).SearchContext), ctx, userID, queryEmbedding, limit)
}

// MockEmbeddingGenerator is a mock of EmbeddingGenerator interface.
type MockEmbeddingGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockEmbeddingGeneratorMockRecorder
	isgomock struct{}
}

// MockEmbeddingGeneratorMockRecorder is the mock recorder for MockEmbeddingGenerator.
type MockEmbeddingGeneratorMockRecorder struct {
	mock *MockEmbeddingGenerator
}

// NewMockEmbeddingGenerator creates a new mock instance.
func NewMockEmbeddingGenerator(ctrl *gomock.Controller) *MockEmbeddingGenerator {
	mock := &MockEmbeddingGenerator{ctrl: ctrl}
	mock.recorder = &MockEmbeddingGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmbeddingGenerator) EXPECT() *MockEmbeddingGeneratorMockRecorder {
	return m.recorder
}

// GenerateEmbedding mocks base method.
func (m *MockEmbeddingGenerator) GenerateEmbedding(ctx context.Context, text string) ([]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateEmbedding", ctx, text)
	ret0, _ := ret[0].([]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateEmbedding indicates an expected call of GenerateEmbedding.
func (mr *MockEmbeddingGeneratorMockRecorder) GenerateEmbedding(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateEmbedding", reflect.TypeOf((*MockEmbeddingGenerator)(nil).GenerateEmbedding), ctx, text)
}

// MockEmbeddingRepository is a mock of EmbeddingRepository interface.
type MockEmbeddingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmbeddingRepositoryMockRecorder
	isgomock struct{}
}

// MockEmbeddingRepositoryMockRecorder is the mock recorder for MockEmbeddingRepository.
type MockEmbeddingRepositoryMockRecorder struct {
	mock *MockEmbeddingRepository
}

// NewMockEmbeddingRepository creates a new mock instance.
func NewMockEmbeddingRepository(ctrl *gomock.Controller) *MockEmbeddingRepository {
	mock := &MockEmbeddingRepository{ctrl: ctrl}
	mock.recorder = &MockEmbeddingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmbeddingRepository) EXPECT() *MockEmbeddingRepositoryMockRecorder {
	return m.recorder
}

// DeleteProfile mocks base method.
func (m *MockEmbeddingRepository) DeleteProfile(ctx context.Context, profileID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProfile", ctx, profileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProfile indicates an expected call of DeleteProfile.
func (mr *MockEmbeddingRepositoryMockRecorder) DeleteProfile(ctx, profileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProfile", reflect.TypeOf((*MockEmbeddingRepository)(nil).DeleteProfile), ctx, profileID)
}

// UpsertProfile mocks base method.
func (m *MockEmbeddingRepository) UpsertProfile(ctx context.Context, profile *models.Profile, embedding []float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertProfile", ctx, profile, embedding)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertProfile indicates an expected call of UpsertProfile.
func (mr *MockEmbeddingRepositoryMockRecorder) UpsertProfile(ctx, profile, embedding any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertProfile", reflect.TypeOf((*MockEmbeddingRepository)(nil).UpsertProfile), ctx, profile, embedding)
}
